version: "0.2"
language: en
ignorePaths:
  - .vscode/**
  - node_modules/**
  - build/**
  - .svelte-kit/**
  - dist/**
  - "**/*.d.ts"
  - "**/*.map"
  - "**/*.min.js"
  - .git/**/*
  - .gitignore
  - "**/*.svg"
  - pnpm-lock.yaml
  - .env*
  - playwright-report/**
  - .pnpm-store/**
  - .wrangler/**
  - .coderabbit.yaml
  - .fast-check/**
  - src/lib/paraglide/**
  - project.inlang/**
  - src/lib/constants/video-ids.ts
  - .dev.vars**
  - src/lib/server/db/auth.schema.ts
words:
  - aikidosec
  - coderabbit
  - cooldown
  - Daihatsu
  - EDITMSG
  - esbuild
  - eslintcache
  - ianvs
  - inlang
  - joshuafolkken
  - kysely
  - libsql
  - mischeck
  - modestbranding
  - mqdefault
  - noopener
  - noreferrer
  - octocat
  - OEMBED
  - paraglide
  - Qube
  - seekbar
  - sonarjs
  - sonarqube
  - Stylesheet
  - trycloudflare
  - unrs
  - vite
  - vmin
  - workerd
  - youtubei
